version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_KEY=${REDIS_KEY}
      - REDIS_DB=0
    volumes:
      - redis-data:/data
    networks:
      - code-push-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_KEY=${REDIS_KEY}
      - REDIS_DB=0
      - SERVER_PORT=${API_PORT:-3000}
    volumes:
      - ./api:/app
      - /app/node_modules
      - /app/bin
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1"]
    depends_on:
      - redis
    networks:
      - code-push-network

  cli:
    build:
      context: ./cli
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - API_URL=http://api:3000
    depends_on:
      - api-server
    networks:
      - code-push-network

networks:
  code-push-network:
    driver: bridge

volumes:
  redis-data:
