version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_KEY=${REDIS_KEY}
    volumes:
      - redis-data:/data

  code-push:
    build: .
    container_name: code-push-server
    ports:
      - "${SERVER_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_KEY=${REDIS_KEY}
      - SERVER_PORT=${SERVER_PORT:-3000}
    depends_on:
      - redis

volumes:
  redis-data:
